version: '3.8'

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile.prod
    command: gunicorn dtb.wsgi:application --bind :8021
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8021
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      
  db:
    container_name: dtb_postgres
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
   
  redis:
    image: redis:alpine
    container_name: dtb_redis
    volumes:
      - ./redis_data:/data

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:81
    depends_on:
      - web
  bot:
    build: .
    container_name: dtb_bot
    command: python run_pooling.py
    env_file:
      - ./.env
    depends_on:
      - web

  celery:
    build: .
    container_name: dtb_celery
    command: celery -A dtb worker --loglevel=INFO
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      
  celery-beat:
    build: .
    container_name: dtb_beat
    command: celery -A dtb beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

networks:
  default:
    name: nginxproxymanager_default
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume: