# Generated by Django 4.0.7 on 2022-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unic_clicks',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во уникальных кликов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='День Рождения'),
        ),
    ]
