# Generated by Django 4.0.6 on 2022-07-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_group_image_mailing_message_video_delete_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(to='tgbot.image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.ManyToManyField(to='tgbot.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='vedios',
            field=models.ManyToManyField(to='tgbot.video'),
        ),
    ]
