# Generated by Django 4.0.6 on 2022-07-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_rename_mailing_broadcast_alter_broadcast_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='video',
            new_name='file',
        ),
    ]
