# Generated by Django 4.0.6 on 2022-07-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_rename_video_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast',
            old_name='group',
            new_name='groups',
        ),
    ]
