# Generated by Django 4.0.6 on 2022-08-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_alter_broadcast_created_at_alter_broadcast_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('answers', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ответы')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.message', verbose_name='Сообщение')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
